streams:
  rgb:
    type: image
    output_topic: /remote/head_rgbd_sensor/rgb/image_rect_color
    zenoh_key: robot/head_rgbd_sensor/rgb
    queue_depth: 1

  depth:
    type: depth
    output_topic: /remote/head_rgbd_sensor/depth_registered/image_rect_raw
    zenoh_key: robot/head_rgbd_sensor/depth
    queue_depth: 1

  cloud_draco:
    type: pointcloud
    output_topic: /remote/head_rgbd_sensor/depth_registered/rectified_points
    zenoh_key: robot/head_rgbd_sensor/points
    queue_depth: 1

  cloud_cloudini_candidate:
    type: pointcloud
    output_topic: /remote/head_rgbd_sensor/depth_registered/rectified_points
    zenoh_key: robot/head_rgbd_sensor/points_cloudini
    queue_depth: 1
